# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        MainWindow.setStyleSheet("background: rgb(18, 18, 18)")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.inputLabel = QtWidgets.QLabel(self.centralwidget)
        self.inputLabel.setGeometry(QtCore.QRect(100, 160, 311, 21))
        font = QtGui.QFont()
        font.setFamily("JetBrains Mono")
        font.setPointSize(12)
        self.inputLabel.setFont(font)
        self.inputLabel.setStyleSheet("color : #e1e1e1;")
        self.inputLabel.setObjectName("inputLabel")
        self.importButton = QtWidgets.QPushButton(self.centralwidget)
        self.importButton.setGeometry(QtCore.QRect(430, 280, 131, 31))
        self.importButton.setStyleSheet("QPushButton {\n"
"  background-color: #2b4d70;\n"
"  border: 1px solid transparent;\n"
"  border-radius: 12px;\n"
"  box-sizing: border-box;\n"
"  color: #FFFFFF;\n"
"  cursor: pointer;\n"
"  flex: 0 0 auto;\n"
"  font-family: \"Inter var\",ui-sans-serif,system-ui,-apple-system,system-ui,\"Segoe UI\",Roboto,\"Helvetica Neue\",Arial,\"Noto Sans\",sans-serif,\"Apple Color Emoji\",\"Segoe UI Emoji\",\"Segoe UI Symbol\",\"Noto Color Emoji\";\n"
"  font-size: 1.125rem;\n"
"  font-weight: 600;\n"
"  line-height: 1.5rem;\n"
"  padding: .75rem 1.2rem;\n"
"  text-align: center;\n"
"  text-decoration: none #6B7280 solid;\n"
"  text-decoration-thickness: auto;\n"
"  transition-duration: .2s;\n"
"  transition-property: background-color,border-color,color,fill,stroke;\n"
"  transition-timing-function: cubic-bezier(.4, 0, 0.2, 1);\n"
"  user-select: none;\n"
"  -webkit-user-select: none;\n"
"  touch-action: manipulation;\n"
"  width: auto;\n"
"}\n"
"\n"
"QPushButton::pressed{\n"
"    background-color: #374151;\n"
"    opacity : 0.75;\n"
"}\n"
"\n"
"QPushButton::hover {\n"
"    border: 3px solid black;\n"
"}")
        self.importButton.setObjectName("importButton")
        self.inputLabel_2 = QtWidgets.QLabel(self.centralwidget)
        self.inputLabel_2.setGeometry(QtCore.QRect(200, 50, 451, 21))
        font = QtGui.QFont()
        font.setFamily("JetBrains Mono")
        font.setPointSize(14)
        self.inputLabel_2.setFont(font)
        self.inputLabel_2.setStyleSheet("color : #e1e1e1;")
        self.inputLabel_2.setObjectName("inputLabel_2")
        self.inputLabel_3 = QtWidgets.QLabel(self.centralwidget)
        self.inputLabel_3.setGeometry(QtCore.QRect(100, 340, 311, 21))
        font = QtGui.QFont()
        font.setFamily("JetBrains Mono")
        font.setPointSize(12)
        self.inputLabel_3.setFont(font)
        self.inputLabel_3.setStyleSheet("color : #e1e1e1;")
        self.inputLabel_3.setObjectName("inputLabel_3")
        self.outputText = QtWidgets.QTextBrowser(self.centralwidget)
        self.outputText.setGeometry(QtCore.QRect(90, 380, 611, 171))
        self.outputText.setStyleSheet("background:rgb(30, 30, 30);\n"
"border-radius: 15px;\n"
"color : #e1e1e1;")
        self.outputText.setObjectName("outputText")
        self.predictButton = QtWidgets.QPushButton(self.centralwidget)
        self.predictButton.setGeometry(QtCore.QRect(570, 280, 131, 31))
        self.predictButton.setStyleSheet("QPushButton {\n"
"  background-color: #2b4d70;\n"
"  border: 1px solid transparent;\n"
"  border-radius: 12px;\n"
"  box-sizing: border-box;\n"
"  color: #FFFFFF;\n"
"  cursor: pointer;\n"
"  flex: 0 0 auto;\n"
"  font-family: \"Inter var\",ui-sans-serif,system-ui,-apple-system,system-ui,\"Segoe UI\",Roboto,\"Helvetica Neue\",Arial,\"Noto Sans\",sans-serif,\"Apple Color Emoji\",\"Segoe UI Emoji\",\"Segoe UI Symbol\",\"Noto Color Emoji\";\n"
"  font-size: 1.125rem;\n"
"  font-weight: 600;\n"
"  line-height: 1.5rem;\n"
"  padding: .75rem 1.2rem;\n"
"  text-align: center;\n"
"  text-decoration: none #6B7280 solid;\n"
"  text-decoration-thickness: auto;\n"
"  transition-duration: .2s;\n"
"  transition-property: background-color,border-color,color,fill,stroke;\n"
"  transition-timing-function: cubic-bezier(.4, 0, 0.2, 1);\n"
"  user-select: none;\n"
"  -webkit-user-select: none;\n"
"  touch-action: manipulation;\n"
"  width: auto;\n"
"}\n"
"\n"
"QPushButton::pressed{\n"
"    background-color: #374151;\n"
"    opacity : 0.75;\n"
"}\n"
"\n"
"QPushButton::hover {\n"
"    border: 3px solid black;\n"
"}")
        self.predictButton.setObjectName("predictButton")
        self.datasetName = QtWidgets.QTextBrowser(self.centralwidget)
        self.datasetName.setGeometry(QtCore.QRect(90, 190, 611, 81))
        self.datasetName.setStyleSheet("background:rgb(30, 30, 30);\n"
"border-radius: 15px;\n"
"color : #e1e1e1;")
        self.datasetName.setObjectName("datasetName")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MBTI Predictor"))
        self.inputLabel.setText(_translate("MainWindow", "Import Dataset to Predict :"))
        self.importButton.setText(_translate("MainWindow", "Import"))
        self.inputLabel_2.setText(_translate("MainWindow", "Predicting Myers Briggs Type Indicator"))
        self.inputLabel_3.setText(_translate("MainWindow", "Output : "))
        self.predictButton.setText(_translate("MainWindow", "Predict"))


# if __name__ == "__main__":
#     import sys
#     app = QtWidgets.QApplication(sys.argv)
#     MainWindow = QtWidgets.QMainWindow()
#     ui = Ui_MainWindow()
#     ui.setupUi(MainWindow)
#     MainWindow.show()
#     sys.exit(app.exec_())
